name: Latest blog posts
on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:
jobs:
  update-blog-post:
    name: Update latest blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG"
          commit_message: "Update Blog posts"
          max_post_count: "4"
          feed_list: "https://fahmifj.github.io/categories/blog/index.xml"
