name: Latest writeups
on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:
jobs:
  update-blog-post:
    name: Update latest writeups
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-CTF"
          commit_message: "Update CTF posts"
          max_post_count: "4"
          feed_list: "https://fahmifj.github.io/categories/ctf/index.xml"
